### PR TITLE
Task

### PR DESCRIPTION
**Pull request by leducthinh1494**
laravel_quicktask

### CODE REVIEW

**Comment by leducthinh1494** [comment]
ready

**Comment by trangkarol** [comment]
screenshot from 2018-04-10 09-47-20
reabse về 1 commit thôi e ơi

**Comment by trangkarol** [comment]
commented

**Comment by leducthinh1494** [comment]
ready

**Comment by trangkarol** [comment]
commented
e rebase với develop chưa?

**Pull request closed without merging**
